apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

resources:
- configmap.yaml


patches:
  - target:
      kind: Deployment
      name: flask-ks
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true
