apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- serviceaccount.yaml
- service.yaml

namespace: flask-ks

generators:
 - ./kops-secret.yaml


generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true


namespace: flask-ks
